### PR TITLE
Add plugin actions and quick improvements

### PR DESCRIPTION
**Pull request by Gaffal**
Just some quick changes such as plugin actions and selecting ungrouped/grouped objects.

### CODE REVIEW

**Review by FlynnFarrow — COMMENTED** [review]
Pull looks fine to merge but will need to perform testing

**Comment by Gaffal** [comment]
> Pull looks fine to merge but will need to perform testing

Perfect. I've tested and it went fine.

**Comment by FlynnFarrow** [comment]
Hey @Gaffal I would fork this straight away but there is a conflict that needs to be resolved due to the latest update

**Comment by FlynnFarrow** [comment]
Decided to close this since the quick improvements have been added and plugin actions probably aren't needed atm

Thanks for submitting this though

**Comment by Gaffal** [comment]
> Decided to close this since the quick improvements have been added and plugin actions probably aren't needed atm
> 
> Thanks for submitting this though

Alright, no problem. Have a nice week 😊

**Pull request closed without merging**
